// packages/demo-react/src/components/Markdown.tsx
import { marked } from 'marked'
import type { DefaultBlockProps, BlockConfigOf } from '@pageblocks/react'

type MarkdownConfig = { content: string }
export type MarkdownBlockConfig = BlockConfigOf<MarkdownConfig, 'markdown'>
type MarkdownProps = MarkdownConfig & DefaultBlockProps

export function Markdown({ content }: MarkdownProps) {
  const html = String(marked.parse(content))
  return <div dangerouslySetInnerHTML={{ __html: html }} />
}

// packages/demo-vue/src/components/Markdown.vue
<script setup lang="ts">
import { computed } from 'vue'
import { marked } from 'marked'

import type {DefaultBlockProps, BlockConfigOf} from "@pageblocks/vue";

type CustomConfig = { content: string }

export type MarkdownConfig = BlockConfigOf<CustomConfig, 'markdown'>
export type MarkdownProps = CustomConfig & DefaultBlockProps

const props = defineProps<MarkdownProps>()

const html = computed(() => marked(props.content) as string)
</script>

<template><div v-html="html" /></template>
