// packages/demo-vue/src/components/CardGrid.vue
<script setup lang="ts">
import type {DefaultBlockProps, BlockConfigOf} from '@pageblocks/vue'
import { useBlockEvents } from '@pageblocks/vue'

import Card, { type CardConfig } from './Card.vue'

export type CustomConfig = {
  _type: 'card-grid'
  children: CardConfig[]
}

export type CardGridConfig = BlockConfigOf<CustomConfig, 'card-grid'>

type CardGridProps = CustomConfig & DefaultBlockProps
const props = defineProps<CardGridProps>()

const { domHandlers } = useBlockEvents(
  () => ({ on: props.on, blockKey: props.blockKey, blockType: props.blockType ?? 'card-grid' }),
) || {}
</script>

<template>
  <div class="card-grid" v-on="domHandlers">
    <Card
      v-for="(card, i) in children"
      :key="card._key ?? card.id ?? i"
      :title="card.title"
      :body="card.body"
      :image="card.image"
      :image-alt="card.imageAlt"
      :link="card.link"
      :id="card.id"
      :class="card.class"
      :on="card.on"
      :block-key="card._key"
      :block-type="card._type"
    />
  </div>
</template>

// packages/demo-react/src/components/CardGrid.tsx
import { useBlockEvents, type DefaultBlockProps, type BlockConfigOf } from '@pageblocks/react'
import { Card, type CardBlockConfig } from './Card'

type CardGridConfig = {
  children: CardBlockConfig[]
}

export type CardGridBlockConfig = BlockConfigOf<CardGridConfig, 'card-grid'>
type CardGridProps = CardGridConfig & DefaultBlockProps

export function CardGrid({ children, blockType, blockKey, on }: CardGridProps) {
  const eventHandlers = useBlockEvents(on, blockType, blockKey)

  return (
    <div className="card-grid" {...eventHandlers}>
      {children.map((card, i) => (
        <Card
          key={card._key ?? card.id ?? i}
          blockType={card._type}
          blockKey={card._key}
          on={card.on}
          title={card.title}
          body={card.body}
          image={card.image}
          imageAlt={card.imageAlt}
          link={card.link}
          id={card.id}
          class={card.class}
        />
      ))}
    </div>
  )
}
