// packages/demo-vue/src/components/Html.vue
<script setup lang="ts">
import type {DefaultBlockProps, BlockConfigOf} from "@pageblocks/vue";

type CustomConfig = {
  content: string
}

export type HtmlConfig = BlockConfigOf<CustomConfig, 'html'>
export type HtmlProps = CustomConfig & DefaultBlockProps

defineProps<HtmlProps>()
</script>

<template><div v-html="content" /></template>

// packages/demo-react/src/components/Html.tsx
import type { DefaultBlockProps, BlockConfigOf } from '@pageblocks/react'

type HtmlConfig = { content: string }
export type HtmlBlockConfig = BlockConfigOf<HtmlConfig, 'html'>
type HtmlProps = HtmlConfig & DefaultBlockProps

export function Html({ content }: HtmlProps) {
  return <div dangerouslySetInnerHTML={{ __html: content }} />
}
