// src/components/blocks/Observer.vue
<script setup lang="ts">
import { defineAsyncComponent, onMounted, onUnmounted, ref } from 'vue'
import type { Block, EventMap } from '../../types/types'
import { useActionRegistry } from '../../lib/actionRegistry.ts'
import { toArray } from '../../lib/utils'

const BlockRenderer = defineAsyncComponent(() => import('../BlockRenderer.vue'))

const props = defineProps<{
  on: EventMap
  children: Block[]
  blockKey?: string
  blockType?: string
}>()
// id and class fall through to the root <div>

const actionRegistry = useActionRegistry()
const rootEl = ref<Element | null>(null)

let observer: IntersectionObserver | null = null

onMounted(() => {
  if (!actionRegistry || !rootEl.value) return
  const { inview, outview } = props.on
  if (!inview && !outview) return

  observer = new IntersectionObserver((entries) => {
    for (const entry of entries) {
      if (entry.isIntersecting && inview) {
        const opts = { eventName: 'inview', event: null, args: [], blockType: props.blockType ?? 'observer', blockKey: props.blockKey }
        toArray(inview).forEach(d => actionRegistry.dispatch(d, opts))
      }
      if (!entry.isIntersecting && outview) {
        const opts = { eventName: 'outview', event: null, args: [], blockType: props.blockType ?? 'observer', blockKey: props.blockKey }
        toArray(outview).forEach(d => actionRegistry.dispatch(d, opts))
      }
    }
  })
  observer.observe(rootEl.value)
})

onUnmounted(() => observer?.disconnect())
</script>

<template>
  <div ref="rootEl">
    <BlockRenderer :blocks="children" />
  </div>
</template>

// packages/demo-react/src/components/Observer.tsx
import { useEffect, useRef } from 'react'
import {
  BlockRenderer,
  createActionDispatcher,
  toArray,
  useActionRegistry,
  type BlockConfig,
  type DefaultBlockProps,
  type BlockConfigOf,
  type EventMap,
} from '@pageblocks/react'

type ObserverConfig = {
  on: Pick<EventMap, 'inview' | 'outview'> & EventMap
  children?: BlockConfig[]
  class?: string
}

export type ObserverBlockConfig = BlockConfigOf<ObserverConfig, 'observer'>
type ObserverProps = ObserverConfig & DefaultBlockProps

export function Observer({ on, children: blocks, blockType, blockKey, class: className }: ObserverProps) {
  const rootRef = useRef<HTMLDivElement>(null)
  const actionRegistry = useActionRegistry()

  useEffect(() => {
    if (!rootRef.current) return
    const { inview, outview } = on
    if (!inview && !outview) return

    const actionDispatcher = createActionDispatcher(actionRegistry)
    const observer = new IntersectionObserver((entries) => {
      for (const entry of entries) {
        if (entry.isIntersecting && inview) {
          const opts = { eventName: 'inview', event: null, args: [], blockType, blockKey }
          toArray(inview).forEach(d => actionDispatcher.dispatch(d, opts))
        }
        if (!entry.isIntersecting && outview) {
          const opts = { eventName: 'outview', event: null, args: [], blockType, blockKey }
          toArray(outview).forEach(d => actionDispatcher.dispatch(d, opts))
        }
      }
    })
    observer.observe(rootRef.current)
    return () => observer.disconnect()
  }, [actionRegistry, on, blockType, blockKey])

  return (
    <div ref={rootRef} className={className}>
      {blocks && <BlockRenderer blocks={blocks} />}
    </div>
  )
}
