// packages/vue/src/components/BlockRenderer.vue
<script setup lang="ts">
import type {ActionRegistry, ComponentRegistry, BlockConfig} from '@pageblocks/core'
import {provideActionRegistry, useActionRegistry, useComponentRegistry} from "../composables";
import {provideComponentRegistry} from "../composables";
import { type HtmlNodeProps } from "./HtmlNode.vue";
import HtmlNode from "./HtmlNode.vue";

export type BlockRendererProps = {
  blocks: BlockConfig[]
  components?: ComponentRegistry
  actions?: ActionRegistry
}

const props = defineProps<BlockRendererProps>()

const { blocks } = props

const components = props.components ?? useComponentRegistry()
const actions = props.actions ?? useActionRegistry()

// provide registries to subtree components
provideActionRegistry(actions)
provideComponentRegistry(components)

function customProps(block: BlockConfig): Record<string, unknown> {
  const { _type: _t, _key: _k, ...rest } = block as unknown as Record<string, unknown>
  return rest
}

function asHtmlNodeProps(attr: Record<string, unknown>): HtmlNodeProps {
  return attr as HtmlNodeProps
}
</script>

<template>
  <template v-for="(block, i) in blocks" :key="block._key ?? i">
    <component
      v-if="components.resolve(block._type)"
      :is="components.resolve(block._type)"
      v-bind="customProps(block)"
      :block-key="block._key"
      :block-type="block._type"
    />
    <HtmlNode
      v-else
      v-bind="asHtmlNodeProps(customProps(block))"
      :block-key="block._key"
      :block-type="block._type"
    />
  </template>
</template>

// packages/react/src/components/BlockRenderer.tsx
import { type ReactElement } from 'react'
import type { BlockConfig, ActionRegistry } from '@pageblocks/core'
import {
  RegistryProvider,
  useActionRegistry,
  useComponentRegistry,
  type ReactComponentRegistry,
} from '../context/RegistryContext'
import { HtmlNode, type HtmlNodeProps } from './HtmlNode'

export type BlockRendererProps = {
  blocks: BlockConfig[]
  actions?: ActionRegistry
  components?: ReactComponentRegistry
}

export function BlockRenderer({ blocks, actions, components }: BlockRendererProps): ReactElement {
  const inheritedActions = useActionRegistry()
  const inheritedComponents = useComponentRegistry()

  const actionRegistry = actions ?? inheritedActions
  const componentRegistry = components ?? inheritedComponents

  const rendered = blocks.map((block, i) => {
    const { _type, _key, ...rest } = block as unknown as Record<string, unknown>
    const key = (_key as string | undefined) ?? `${String(_type)}-${i}`
    const Component = componentRegistry.resolve(String(_type))

    if (Component) {
      return (
        <Component
          key={key}
          blockType={_type}
          blockKey={_key}
          {...rest}
        />
      )
    }

    return (
      <HtmlNode
        key={key}
        blockType={String(_type)}
        blockKey={_key as string | undefined}
        {...(rest as Omit<HtmlNodeProps, 'blockType' | 'blockKey'>)}
      />
    )
  })

  // Only introduce a new provider when props override the inherited registries
  if (!actions && !components) return <>{rendered}</>

  return (
    <RegistryProvider actions={actionRegistry} components={componentRegistry}>
      {rendered}
    </RegistryProvider>
  )
}
