// packages/vue/src/components/HtmlNode.vue
<script setup lang="ts">
import {type BlockConfig} from '@pageblocks/core'
import { useBlockEvents } from '../composables'
import type {DefaultBlockProps, BlockConfigOf} from "../types/props";
import BlockRenderer from './BlockRenderer.vue'

type CustomConfig = {
  text?: string
  children?: BlockConfig[]
} & { [key: string]: string | number | boolean | null }

export type HtmlNodeConfig = BlockConfigOf<CustomConfig, keyof HTMLElementTagNameMap>
export type HtmlNodeProps = CustomConfig & DefaultBlockProps

const props = defineProps<HtmlNodeProps>()

const { domHandlers } = useBlockEvents(
  () => ({ on: props.on, blockKey: props.blockKey, blockType: props.blockType ?? ''}),
)
</script>

<template>
  <component :is="props.blockType" v-on="domHandlers">
    <BlockRenderer v-if="props.children" :blocks="props.children" />
    <template v-else-if="props.text">{{ props.text }}</template>
  </component>
</template>

// packages/react/src/components/HtmlNode.tsx
import { createElement, type ReactElement } from 'react'
import type { BlockConfig, EventMap } from '@pageblocks/core'
import { useBlockEvents } from '../hooks/useBlockEvents'
import type { DefaultBlockProps, BlockConfigOf } from '../types/props'
import { BlockRenderer } from './BlockRenderer'

// string | number | boolean covers all valid primitive HTML attribute values
type HtmlAttrs = Record<string, string | number | boolean | null | undefined>

type HtmlNodeOwnProps = {
  text?: string
  children?: BlockConfig[]
  class?: string
}

// Base config type for HTML blocks — does not include arbitrary HTML attributes
// because [key: string] index signatures prevent Omit from working correctly.
// Use `BlockConfig & { [key: string]: unknown }` in your own code for full flexibility.
export type HtmlNodeConfig = BlockConfigOf<HtmlNodeOwnProps, keyof HTMLElementTagNameMap>
export type HtmlNodeProps = HtmlNodeOwnProps & DefaultBlockProps & { on?: EventMap } & HtmlAttrs

export function HtmlNode({
  blockType,
  blockKey,
  on,
  text,
  children: blocks,
  class: className,
  ...attrs
}: HtmlNodeProps): ReactElement {
  const eventHandlers = useBlockEvents(on, blockType, blockKey)

  const domProps: Record<string, unknown> = {
    ...(className !== undefined ? { className } : {}),
    ...attrs,
    ...eventHandlers,
  }

  const content = blocks
    ? createElement(BlockRenderer, { blocks })
    : (text ?? null)

  return createElement(blockType, domProps, content !== null ? content : undefined)
}
